version: '{build}'

# Uncomment this to enable the fast build environment if your account does not
# support it automatically:
image: Visual Studio 2017
skip_non_tags: true

environment:
  matrix:
    - BUILD_TYPE: Release
      COMPILER: MSVC17
      PLATFORM: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - BUILD_TYPE: Release
      COMPILER: MSVC17
      PLATFORM: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

#    - BUILD_TYPE: Release
#      COMPILER: MinGW-w64
#      PLATFORM: x64
#      TOOLCHAIN: x86_64-7.3.0-posix-seh-rt_v5-rev0
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#
#    - BUILD_TYPE: Release
#      COMPILER: MinGW
#      PLATFORM: Win32
#      TOOLCHAIN: i686-6.3.0-posix-dwarf-rt_v5-rev1
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

build_script:
  - git describe --tags
  - mkdir build
  - cd build
  - if [%COMPILER%]==[MSVC17] if [%PLATFORM%]==[Win32] cmake -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..
  - if [%COMPILER%]==[MSVC17] if [%PLATFORM%]==[x64] cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..
#  - if [%COMPILER%]==[MinGW] set PATH=C:\MinGW-w64\%TOOLCHAIN%\mingw32\bin;%PATH:C:\Program Files\Git\usr\bin;=%
#  - if [%COMPILER%]==[MinGW-w64] set PATH=C:\MinGW-w64\%TOOLCHAIN%\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
#  - if [%COMPILER%]==[MinGW] cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=C:\mingw-w64\%TOOLCHAIN% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..
#  - if [%COMPILER%]==[MinGW-w64] cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=C:\mingw-w64\%TOOLCHAIN% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..

  - cmake --build . --config %BUILD_TYPE%
#  - cmake --build . --config %BUILD_TYPE% --target face
#  - cmake --build . --config %BUILD_TYPE% --target swagger
#  - cpack

artifacts:
  - path: build\cpp_src\server\cbinding\Release\reindexer_embedded_server.dll
    name: reindexer_embedded_server


#test_script:

on_success:
#- cd C:\
